---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCAMoLicd1002W+zmZgwAyLPsQ0buEPbF+U/YsK2hdlpUEXDmdICnWazmsKd28IW9oKrexXulKte2GhgfMjF1eyUuSChpQucDh8TlyiFYv6zJKfHeFuaf+HbLAqnrAh2LAO6/uTEo4hFb+Wh864keqOuECSQlGUypfwN3r7JWVWBNWYb6QyUH0Im7Xa7IGX85x5/TYM4PXvIMVtYpEM1Ep49/1gElLBkKPMl3ycSiAEPfhmMEuCh9dc1IsHmp0+MDsWMPuTl5Lg77T9u/A3nPwntp9DeImE2h0wDpSUAC0KrRD9KJpAfMvnbPwtkysmP1idTgOrxItTVLV0E6xHzaNOVTCHZa45mQUhQgQoALvWMPqBfH7QScZZUHQj+JW/LlGgIQD6v4UxMJ+QmIk0bD8fbUNehiHJXRoSdzRN2OMfLrUiRMLyPMBd5M9t+v8lAX+6k6a/GUnGjVJuiWxz0o6NKZ0Mj8Iyrcftm9WVCgOUUqwovmZ1c3k/bkmsv20/O8rsScF6o8sA1FRftmuET9ERVR0desXgc3hpn/4mGGxkEfkbSlZM82iiTSXm1Zt+477cHUOVUEfzIBE9qx8rL0pQUFYpIZcEnvEyfKX1aVIRaTbWVWZdPy09df2EqBYxjT47CFT2iq0SomP2SzFJ8XIZRqClGcaiUOErWmRIaUO6anOsXfr/gqzOJbtfNIF7ydnjH02NNO8Me6fdZyJxiwbrol9g5di+vM7VIU8h5/hbHwucdej4wvZO5Ri6ozQxXhkupZIp6dpUP8byv4XJ/DYDyBuuPCzuElC4vz9gNB+zD5cvjVXud6zOv2jgB2+AsNYRBdhoApkeyNmZfQGds6t62cE/8VUs8V4MCD084I1clZGVbj6h9wTxxAX7DXF7OgkhiKH/0V1YOcSYaFUBFUFZ0Yl6RP2sjRphMp7ZsAEWiJKLcUlK5oXFA8hTOgs4SRLljpLI79WFYvZlLbZAzLDZSlMiu+Xxqh3EYolgmsQMOvSKKa5eVg9cTKT1+1WVbKLYRAE2hDRR6ftmY/MzQQcLSA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
