---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: auth-secret
  namespace: default
spec:
  encryptedData:
    ACCESS_TOKEN_SECRET_KEY: AgAFw2vTY8zTJjb+N+i/BrGR4NijLwfJv2d34QkwaBtKXQjgvMPcthaV0O6dc4w0wdbGoiWMBVFbjppMSOVdkn68jWvtx0+WGGKWf0MaieruqEwepv3fMP4UpFu11cZn6O71dlzWPLEIxTOgU15IhxKQnnRXWf/VTAXvf4lMqNdcntjb7xfWlaPinEXbCpppBe1tzh2WDGrclVIavtJbjfHx/eXwNrsYTxrCCZxBEPGg4a+d/oeKky8Kh4InoyQOi8FcxItY6YYhsP8x1+dsqpaBK8BwXtc6FyCjuXTue3DeVW8KLwgG0nyC1C7s1fM+rHl3Z/pM4fdv7CbezUr4+c1ppSxHo1StBWJRPZQDyj0Pn9Qo1HyxU6j3d5ZeDUNd75pmXGAsv+ERDq9Bn7KufXHYtYd+y0Jvlq+eRvrAOa0alW/IOpb1BLMfpLlI9GqPeDVcsC6ZyOOFPbA/O4/ua5tPiyJlE5/IEng0fq3hpAdI0+yk7dsUVCIIbx/+zOBOLa4MCC9OBQ4UQLSd5oWcVslk2wJ8RbsOuTUvnpNcox6vVWlYEYs81Hd8lV2TbawqNJbWTA01GQGfk2b588bJlu+7yN/ijvgyerD5e3DlxIhYOOTsE67Jq21Zq1V35E4hBZDwUiPoo9pvmQU8vwE1+Ky4iyM7QJhiq/3gcxVXZPZ66FEuF9BqwhI+cQp1yXWAz1MdnEt0ejRJmoEkzg==
    REFRESH_TOKEN_SECRET_KEY: AgBaQzzSvqsphMPi3lgxh9hbx9WkjxkKaqJx6Rg3pe5krUlW9TnuJtDm7U8Ilqsyl39vgZOvaCg0oBCnTbDKl6wfLDJOgfG6rcULII+jTwSMoLLKA2DXAAZ7L8kSt/C4oAUo+8kNbqPGeDONLbuVA4rZlLg7eQQiKvgqRcq4YU7N6WcKsxrQB+Inw0T1nBNcr7tYRixMz7IdJl/fdUCG0dVEecCc5XnxGgV0EHnwp/wpF/f3T72NEPqQl6sCK11Zk7uV27eWBJLQL5MQtdBhdI7i3AIvs87E2fSO15wmNy42l9bzNQOw2T7huscQfGsEAsVsHRkjjLiJdaSYUdHxnK5A5tIUr+6EsM4/3cuHN3oXGJS1X58Ro1J4FVk7Udo0Gl1rDRCaCGHu2zUJ8fYIEP97HD8+URpRkzkxUlRWGVkusjg2Dgmgz5R3m+Lne65U0OyEN4F9kPf3NGyFrnUiUFZJrR1a1kX6yUan6LOnPRVw2d5rl/xuFTvg7K2QgN8kGXSv5dJbjOiV3XGwcxf8DEnHiu9bL8LvJVxc5NFUBfY4cXOH4RJQTK2+9pOZCh8V2sZyoRm0SSnn0gsrBVDVJaPOWdMPwBdqFFoYHDX8DKoHQlW8moshUXk8kBVQzMIz+c3SZw7o9I3E5igaqPcxzOFIm42zsiy/Vo36uMHGEhSWa3z3SE+Uzh8gnI19DaDI2Hg2cJ1fPlGXdH+1iL6GkG13oQm2U9TBqLMioHOpGgosVrE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: auth-secret
      namespace: default
    type: Opaque
