---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBQPPMxVgd+mgFuhNivRVe+aFD74Sec5lGSg/MiT2gOIXkv8HpInoc76Zd7/wQCyjVyqxUKH+sOksaqne+ViAXcEPe+3T8p9f4Ye0dL/bdG54vuheHEByIjcEsXxmWoB3qrqmZFDKq+H2hjM0Tg4pytORpebzplhDukDD6bA2o/y0fcStzPSIT2g3/mQZe2OTkSiTlGkOqlGA+hD3JLNg5/Zi6vUYnYmp86iTPtb2Gak9IF+4jiYS1RZPxB+S5u7UBMj1tSsOunA71ipR6LYZKIk7VmaYWFMMdixDzA+UhzTLkuLrc4kAj3KNLte7UrLZy0PKIEuTkpAhWu7VabCLLFJlimMf8CynprFNFMPoDdhvMy6LPO+eX197ZAPM4kkSeHvxC51YujsKyK2aa5Vtz0WTFQfI2/JvDBom2coXfrNgvaQg9+5LCc2cU4HMO8yuHBoUhs/MB/MEKMDtfDPWBEliTv05R9c60Ca/TCL5oDv0KNBHWO9snDiSMsxYTYrNy329EkQaj6mQfca7EQIzsy+3gHTI+7r8SKn7BnC25M+kZ5ZuOt8GaFYpLZ4mMMpZKCpJHN/4YpzFeUcWStvo/8uVc9DO4gfPqEgYl7wZ5MylLSaTn3V++FCuMxunRUHCne/L678rI1+1xDQRxAxJ6N3XSVMvRAvuJlNLrX7FsQbsjHpHtUCJ3PM1s1eI7NynCfF5twXa6eYoNh2YMigkg0yp7k81YZROmazdNeR/wGlrsZy9mk7MvtXVVF40qTyjRCAG/BuPkhK9KNDaGREAkzdxUhcilvk9zgGTTbJvYAHc2pyNYoKWdeSGZFySpw2JtSRDMGJUyeansSF+PnDJrfj3ieH40zrqux2lcVRwIolFV041kAdCWye/guHH5r2VNcHjp2na287w54k9G0SJ7oSKFxyxLtGuUAqpxoYFFZxlPW6SNlRjrXQAJR3571XHv5jGK7KYGDKzKCkZAf03Y5FF0SLe5E6RKKRuDYlb/feEfofJwziHpIpjTuQ3zMtIF66O/uSfoUGhiH5ijycJcRTQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
