apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vasapolrittideah/money-tracker-config
    targetRevision: HEAD
    path: k8s/auth/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-service-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
