apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: auth-service
            env: dev
          - service: user-service
            env: dev
  template:
    metadata:
      name: "{{service}}-{{env}}"
    spec:
      project: "{{service}}-project"
      source:
        repoURL: https://github.com/vasapolrittideah/money-tracker-config
        targetRevision: HEAD
        path: k8s/{{service}}/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{service}}-{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
