---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCOF0RTRV45ttQkoOthi2LMscUugmn8qwwkvgEWEYZ0e2OWUJEMhYSyFbdcVixrCdYIiUv1j1aSc4Ee3kzbnUK8JYcwaG54jXviwPDkRJFPYMHlegZIPQotXMPPhnENLOQU23ickUgcJK5H/iUB0p6usRLvUJT09rBAy0A2jUKIiQdhwgJeP5bvkMb8QI6NLBZWReUlBdsg0D0drpuNnHvp3Bujc+qm2CswhA62ghf+aQIuBLTkQ9i+PHCF20/RJxK6wsIUjiF5QJ1Yl0HHkiORyNn3ODCSEtEDdyfrBsqoBfuQDz/8y0VQY26Bd2m0tUX3kdGHxZydc7I/I8L5woVdeW9JABLTrdD6uu22CaRyHNcNzw4bB8WsWwFx77I9VO10ukMrRtS81k6fYKlC+1rxwikhWScILhzEUCTvLkIkA5++49QTF7iv8tRgIAeGP24MtY4DfqULwYBB5jf+YUQbQOwa1TeR+QmiSVy6bwrG0fk2L9lHQbxixj/xhrJWxyt7ONoiUOedzSny3uIdDEN4vkOpY9LpQbxOHmemw2LGOxU6F2/Prlt8En2CcYxPAnClfBSVQLWeurwPToY45aB6YbT9Y+X9qrTGNnKv/61OPvdLtEQNcWDFlNcNf6FaIMyPSNPLaObexBpKZjPQyZfbBBEjOhdSL0rD/WLrYm5xKFlSeUgVhako+iCwzSQAMrF6PUp+BDEjZYyBdCTLAqxfgjR63k2fqIU6y0wLf78y+Ua2j4iCwn/nIaMDQc/tCHVkBDSodNsmY0+heCOcQhw0mpETkm0ff6+iKIkG/L/BhgVwrRKgjB/7xq06pYyI3NBxVeRgS881tBwrXfcuHdVLUTXM+AxQykRozde9MaV1oxQnhjqHA8Flz6BN+Wce90rpIozmdZAIn4hXvGS+uXoYXlAM5NAs/k4k/tlMsMy8pX0ltgj4CSy/Bsw3lU8sCD1/mvnKS1FXaHY+5IFEEDZ3kWGA5PcXurI/n3RwRSxgr1fLGla9AdXBlRczWBXwBvluuquJe72T5eqozO+1aSAP1w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
