---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgA32IVYv6zbCJ3tBRaYocowcM/+R900dl71jHujJEUAMexGm9ni5K+bchV0BFCG2q6YjAR8IypWXLLsBNkzaAAbDupuqRnBjJBWa70cOEVl4xZxexybnBB1UhOy6dE3nMIYWl1x2oonX84oXmyBwif4ljlpFl1krzKhGLZF9gGXhufATftobKQEC27pnM7q3oquqpfX4nmBVI1aqhTFGTSAb4BLUWPTBuB3PICyMdb1PdUffhM7snQCgy2IZoLYnOM3xkiOpWaybH0C6nRwVlHMv9g6ovi+z4zjgyoHj6r12pnCHF7qxBB1aox49COwB94EIthp5sY5CYmxKkhgXTLEDvaSZho0K1/QjUPiY3qJLi4sFY8axso8YVPds5gzvAex7g89fRT4vx9vLloctWWv52Qali8HdlcJReSZPpfjAF9Y7msXmAGA3ZIEpF6Gr3/tVHn/5l3lXEmSu9Cn2PEgzrCyBTs53M1e2kSnXXHSFGZgWkzD7ywymct5Vx6ehpvT8JEfJGy+rUO1oVVW9Yx0gixFakg0Nad4KELWWRAqnraO0dF9h7lLQZiIOowFSyBeUDeVlX3wNDjwAuy9/sV32g7EQfAnJO3iKcnmRGVuJv2jUKHTqpxggrHCVa6mP4FGXFMjrdW7O9D3hgWqj2TEkaubORE+pppXoNik6yxD9gyC4pHelhupHQbXMAL/M9q6cZxTXYskqQzpclvLP+yiRa51EaCi6QklGMDst6U4wVvmKhysN0i8vr/1CBOi4ZXh+HUDTOyzkTzmAPkBRyagWSpBUGWxsx2c6wDKzXKt9jG6e2wyBGb5jJtGtpAsydiKh/Vk3w4VGAHyQoAmXhrbXGc1S3MGKvcDMBxCjnbScZIFMkGpe8dC7wbkcgcP3wPcXPnWnsd56si9Qu9CoHugZrS8hw0Y8jzZ7vFRS69l+O5pkYZSFppJCW514Q6hjIu9DgXxAyW145IpPGoZ3CjutQ5wNYaPwxswwI9JL4SnMRBaVXnmaiZ27xJwvqVq76iqBiBW6wa4Tcv2vgl3l11thw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
