apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: auth
          image: vasapolrittideah/money-tracker-api-auth:latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: ACCESS_TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ACCESS_TOKEN_SECRET_KEY
            - name: ACCESS_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: ACCESS_TOKEN_EXPIRES_IN
            - name: REFRESH_TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: REFRESH_TOKEN_SECRET_KEY
            - name: REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: REFRESH_TOKEN_EXPIRES_IN
            - name: AUTH_SERVICE_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: AUTH_SERVICE_HTTP_PORT
            - name: USER_SERVICE_GRPC_CONNECTION_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: USER_SERVICE_GRPC_CONNECTION_HOST
            - name: USER_SERVICE_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: USER_SERVICE_GRPC_PORT
