apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  POSTGRES_HOST: host.docker.internal
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DB: money-tracker-api
  USER_SERVICE_HTTP_PORT: "8000"
  USER_SERVICE_GRPC_PORT: "9000"
