---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: user-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAawY+WSXzN6uZE5gO5NxVyZ3AqkjrcpFlGPmuBSezqfKjmbSPFDIxhTXLqS6HAdkbTqQwNpsPIBuM6np8WP5kloO1I105BTKZUUFOkGmYTjljMnYFyN87Rtc3Dsc0tgiZWhXmURVePn4fhafvYkf+en556cJ4LQECMPxRcoRHTULyLUbYpXToM8hXFPukuRpSb2UA7swRka01DtotkGYYpeirkGLQ7SBPfBfGfcAeJrHSmXVHhTcyxVlebMWFpwvGUDxTsi374suoD5Ouzgk1N2hFdQS/oskEsEBalBSDo8PA7S7bhrbftlipJc9AVMSRgG1D343/TpJiAyp/Q1X8Qd94OEuSp002HOzxt3eDnsEwjGH65ERvhgz9+Dfn0OtQavwH2RLfA8hkMHigArajmRgASyvcZhfaq6qntpsVjTd+6X6VPk2XKj6PGI2g4EmHXwjNTzY7MqdQw0kWVbhCRZ0DrDKih1sfAZBfOwtn3USJtHeEdkRuM2q+NJUY48o/tgzBVn7dXqbJ0dHNB1x7egq73tgLlWlmEsqhyTbKCVfYBLOT6EJ4/oo3+tzGnJpZVn26TsjnzzZBuc2t5j+emU8MQh/7qQxw9qzgy8FCfFTMAlQ99KAiy1Kcevbgv9ii9nDjnEfQffF652gowrTszrryayDDI8NKxCHj8rkGFklQiiL7x97mH+HeLXb+Uts9NWEnbEnZXEwxh/g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: user-secret
      namespace: default
    type: Opaque
