---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: user-secret
  namespace: user-service-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCDcCQ3+un035qxaVxsWq4uZFqGDFjllFgYiKULZhCdFwAMv/Nb2jVrBe9IK9ESDd84W5VU1nY13qLqLNXAHlkhnOw3cI+0RotQvh0eGedBStJwztMOWzxipmjvgiui878PCMrYVNh0JZKbSsygPAWfGrOrwaYyyCK+KYTamsB0WIwqUfeT0wzdflDlLstiY6WskdpEil/mVRyKHeP5ntRj8tAmhxpRHPuug1y+Pk2878RkXc6zCTdVUF/nGRjNbVKHzYQIMITgOLW9q9XVHedpgjneoos1nQbGFRxCCgVjpjYRecWVlpbjksMbFsK6eAhM0gA8JkUqXOJHiPWplcnb5snpneTcMLUor1TYH+zXktlOFWXvbs6SN6ULQb5xJcVd4zIxOzkGraMugiXXzcqXvP2Si7vOvfnO9yLCb1Llg5nSHoR35T83pxXUwWhs6bOOQ2dvfbDTowMB9ed5vIbnUlyqeAFv5iA98QxJ3qT31IHN10+buTg+h/ooM3200Ae33bLMiU3EoxMsexd3C0QUbQuvF+FLjIrUwbQVtqAHp3m9kUnR3hG1LyGY1dRxek7xlORXU4DvvYWaBDxx2iXhEixrb8afVGRM1GNJTHb5OGJLmqVKWp3et9El925iFU9zsPKoWQXsfefqJPhY5IKUrMlGNQh5W3BmP2LlMQarCHa66WUG6RroCNigs2kK8YRqVCMaKJa030GzYA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: user-secret
      namespace: user-service-dev
    type: Opaque
