---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: user-secret
  namespace: user-service-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBb1BiCwEm9jOXoK+C7u2HoOIajtHNVzALi+Ev6/7XBFqDmOfc3H5KYDa8udIZaUZNHi0t4jztnBtDjMoiwDoAp0f8rHSyCK0ckmDUa/tjeXGGZFfr0LdrD/8AyRFeCuHTykZrQtYT8lP1FQQrqJN+gGxe7C8jVqrDtmwwI8X5a9otlyK3Y111Zd4dxLeHM5B82pXSbTDrA8Rsuj0bjBhxgYQC6k6GbXvoKsH1Dz0Stboru1uQhZh6IYXJM7foPAsyfNLIKiuTa4w2JSljrG/AygM70fRHRKd93wsZCbSOCA3T6rUvPLSPt0M9RG67V5RxMXqLtFiZVeGoo8sk8NCp6tVEOFiopiJbaZP+ELR4YjmH1NssvELo2gnECDwIkU8nOG71w7TX5uq9KspWzyA16hksZQPHSMpahs8wU8+h79txLDJOMTtUYrbz5/vD56BaDM2LLL8kXE2pradcmOdSLivWeLnR8eUYij93hg0XglwvuiqqF3BX0oH3e91syB2qZndCIvGzlZ6iqzgJdzVSMXb7Fl+Mm2ywZJInpMjXwQ80NnA+zu3opfp1O56hY4rnmXHNJWHROFhonYE27V/vo5qHY1vwLs1922i6wfSGV6+QVGQ+4zsN8pBVvtnC3HyGMpoMkQBM2i6DSWJgEp4XMDbDnbkeBdNRTJXloQlqFmnh4BfAQPLFBPOufEYKRQZDZLsIHSrqQrRmf5A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: user-secret
      namespace: user-service-dev
    type: Opaque
